{% set name = "cstag" %}
{% set version = "0.4.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/cstag-{{ version }}.tar.gz
  sha256: d61f485f39f658780f34d8d1d1aa863cf50f262bb7651839cb16459bedb6f4bd

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - setuptools
    - wheel
    - pip
  run:
    - python >=3.7

test:
  imports:
    - cstag
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/akikuno/cstag
  summary: Python module to manipulate the minimap2's CS tag
  license: MIT
  license_file: LICENSE
  doc_url: https://akikuno.github.io/cstag/cstag/

extra:
  recipe-maintainers:
    - akikuno
