{% set name = "DAJIN2" %}
{% set version = "0.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/DAJIN2-{{ version }}.tar.gz
  sha256: 913855dd92dd6d3c40511b4e0efd898b0ca4311f2158086f0f9ef36ab300afb0

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - numpy >=1.20.0
    - scipy >=1.6.0
    - pandas >=1.0.0
    - statsmodels >=0.13.5
    - scikit-learn >=1.0.0
    - mappy >=2.24
    - pysam >=0.19.0
    - openpyxl >=3.0.0
    - flask >=2.2.0
    - waitress >=2.1.0
    - jinja2 >=3.1.0
    - plotly >=5.0.0
    - python-kaleido >=0.2.0
    - cstag ==0.4.1
    - midsv >=0.10.1
    - wslpath >=0.3.0
    - rapidfuzz >=3.0.0

test:
  imports:
    - DAJIN2
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/akikuno/DAJIN2
  summary: One-step genotyping tools for targeted long-read sequencing
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - akikuno
