{% set name = "DAJIN2" %}
{% set version = "0.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/DAJIN2-{{ version }}.tar.gz
  sha256: e7f72e3039c7d8c217534b388e7e0967832983fe8eebca006e4e014372cf0805

build:
  entry_points:
    - DAJIN2=DAJIN2.main:execute
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - make
  host:
    - cython
    - python
    - pip
    - setuptools
    - zlib
    - xz
    - bzip2
    - libdeflate
    - libcurl
    - openssl  # [not osx]
  run:
    - python >=3.7
    ##############################
    # to install pysam==0.19.1   #
    - pysam ==0.19.1
    - bzip2 ==1.0.8
    - libdeflate ==1.10
    - libcurl ==7.88.1
    - openssl ===1.1.1q  # [not osx]
    - xz ==5.2.6
    - zlib ==1.2.13
    #############################
    - cstag ==0.4.1
    - flask >=2.2.0
    - jinja2 >=3.1.0
    - python-kaleido >=0.2.0
    - mappy >=2.24
    - midsv >=0.10.1
    - numpy >=1.20.0
    - openpyxl >=3.0.0
    - pandas >=1.0.0
    - plotly >=5.0.0
    - rapidfuzz >=3.0.0
    - scikit-learn >=1.0.0
    - scipy >=1.6.0
    - statsmodels >=0.13.5
    - waitress >=2.1.0
    - wslpath >=0.3.0

test:
  imports:
    - DAJIN2
  commands:
    - pip check
    - DAJIN2 --help
  requires:
    - pip

about:
  home: https://github.com/akikuno/DAJIN2
  summary: One-step genotyping tools for targeted long-read sequencing
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - akikuno
